# Generated by Django 5.2.17 on 2026-09-02 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('section', models.CharField(choices=[('vegetables', 'Овощи и зелень'), ('meat', 'Мясо и птица'), ('dairy', 'Молочные продукты и яйца'), ('grocery', 'Бакалея'), ('canned', 'Консервы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Отдел магазина')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Адрес')),
                ('summary', models.CharField(max_length=280, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_servings', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Базовое количество порций')),
                ('prep_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Подготовка, минут')),
                ('cook_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Приготовление, минут')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=10, verbose_name='Сложность')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианское')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на фотографию')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт.'), ('tbsp', 'ст. л.'), ('tsp', 'ч. л.'), ('to_taste', 'по вкусу')], max_length=12, verbose_name='Единица')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='Примечание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Номер шага')),
                ('description', models.TextField(verbose_name='Описание')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Шаг приготовления',
                'verbose_name_plural': 'Шаги приготовления',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'order'), name='unique_recipe_step_order')],
            },
        ),
    ]
